services:
  redis:
    container_name: redis7
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./configs/redis/redis.conf:/etc/redis/redis.conf:ro
      - ./third_data/redis/data:/data
      - ./third_data/redis/logs:/var/log/redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3

  mysql:
    container_name: mysql8
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./third_data/mysql/data:/var/lib/mysql
      - ./third_data/mysql/logs:/var/log/mysql
      - ./configs/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "-u", "root", "-p123456", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3

  jaeger:
    container_name: jaeger-latest
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.25
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./third_data/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./third_data/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v3.0-beta
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MQ_TYPE: woodpecker
      MILVUS_AUTH_MODE: 1
      MILVUS_USERNAME: root
      MILVUS_PASSWORD: 123456
    volumes:
      - ./third_data/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

  attu:
    container_name: milvus-attu
    image: zilliz/attu:v2.5
    ports:
      - "8000:3000"
    environment:
      MILVUS_URL: milvus-standalone:19530
    depends_on:
      - standalone

  app:
    container_name: api-rag-demo-server
    image: debian:12-slim
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./api-rag-demo-server:/app/api-rag-demo-server
      - ./configs:/app/configs
      - ./third_data/log:/app/log
      - ./workspace:/app/workspace
    working_dir: /app
    command: sh -c "apt-get update && apt-get install -y ca-certificates && chmod +x ./api-rag-demo-server && exec ./api-rag-demo-server -conf=configs/config.local.yaml"
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

networks:
  default:
    name: milvus

